config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :bands
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord

    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: { message: "Password Field can not be blank!!"}
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: { minimum: 4, allow_nil: true }
    before_validation :ensure_session_token
    after_initialize :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return user if user && BCrypt::Password.new(user.password_digest).is_password?(password)

        nil
    end
    
    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end     

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token # this is for convenience later when were comparing session tokens in the views, I think?
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # skip_before_action :verify_authenticity_token

    helper_method :current_user, :logged_in?

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token]) # need to use lazy assignment, why isn't this working in the application.html.erb view?
    end

    def log_in(user) 
        session[:session_token] = user.reset_session_token!
    end

    def logged_in?
        !!self.current_user
    end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    
    def index
        @bands = Band.all
        render :index
    end

    def new
        @band = Band.new 
        render :new
    end

    def create
        @band = Band.new(band_params)

        if @band.save
            flash[:success] = "Congrats on creating a new band!"
            redirect_to bands_url
        else
            flash[:fail] = "Please check your band name"
            render :new
        end
    end

    private

    def band_params
        params.require(:band).permit(:name)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        # debugger
        if user
            log_in(user)
            flash[:success] = "Welcome! Login Successful"
            redirect_to user_url(user.id)
        else
            flash[:error] = "Try again with the right credentials!"
            render :new, status: 401
        end
    end

    def destroy
        current_user.reset_session_token!
        session[:session_token] = nil
        redirect_to new_session_url
    end

    private

    def session_params
        params.require(:session).permit(:email, :password)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            # debugger
            log_in(@user)
            flash[:success] = "Your Account has Successfully been Created!" ## where do I put this on the view? Does it go in the show? new? 
            redirect_to user_url(@user.id)
        else
            render :new, status: 422
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end


    # def index # not sure that I need this, I put this in there so that I could see if the users were being created
    #     render :show
    # end

    private

    def user_params
       params.require(:user).permit(:email, :password) 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/index.html.erb
<h2>Check out all of our Bands Below!!</h2>

    <h4>there will be more shortly, promise....</h4>

    <ul>
        <% @bands.each do |band| %>
        <li> <%=band.name%> </li>

            <%end%>
    </ul>

app/views/bands/new.html.erb
<h2>Create a new Band! </h2>

<form action="<%= bands_url %>" method = "POST">

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <br>
    <label>
        Band Name: 
        <input type="text" name="band[name]" />
    </label>
    <br><br>

    <button>Create Thy Band!</button>

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <h1>Music App</h1>

  <body>
    <% if logged_in? %>
    <form action="<%= session_url %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">

      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <button>Log Out</button>
    </form>


  <form action="<%= new_band_url %>" method="GET">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <button>Create a band!</button>
  </form>
    Current User is: <%= current_user.email %> 
        
    <%end%>
    <%= flash[:success]%>
    <%= flash[:error]%> 

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create a New User</h1>

<form action="<%=users_url%>" method="POST">

     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li> <%= msg %>  </li>
        <%end%>
    </ul>

    <label> 
        Email: 
            <input type="text" name="user[email]" />
    </label>
    <br>
    <br>
    <label>
        Password:
            <input type="password" name="user[password]" />    
    </label>
    <br>
    <br>
    <button>Create User!</button>

</form>

app/views/users/show.html.erb
<h1>User information</h1>

<h3>  <%= @user.email %> </h3>
<h3>  <%= @user.password_digest %> </h3>